# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = "1.0.137"
clap = "3.2.5"

[dev-dependencies]
